-- First, grant schema usage
GRANT USAGE ON SCHEMA public TO postgres;
GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO service_role;

-- Then grant table permissions
GRANT ALL ON ALL TABLES IN SCHEMA public TO postgres;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon;
GRANT ALL ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role;

-- Grant sequence permissions
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO postgres;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO service_role;

-- Set ownership of the schema
ALTER SCHEMA public OWNER TO postgres;

-- Disable RLS on all tables
ALTER TABLE IF EXISTS "User" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Analyst" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Newsletter" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "NewsletterSubscription" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Interaction" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "AnalystCoveredTopic" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "AnalystAccess" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Content" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Publication" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "SocialHandle" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "SocialPost" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Briefing" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Alert" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "ConversationSummary" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "AnalystPortalSession" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "CompanyVision" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "ExclusiveContent" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Testimonial" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "CalendarConnection" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "CalendarMeeting" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "BriefingAnalyst" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "GongConfig" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "ActionItem" DISABLE ROW LEVEL SECURITY; 